# Generated by Django 5.0 on 2024-11-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TallerMecanico', '0003_mecanico_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='datos_completos',
            field=models.BooleanField(default=False),
        ),
    ]
